export { default as Logo } from "./Logo/Logo"
export { default as Button } from "./Button/Button"
export { default as Footer } from "./Footer/Footer"
export { default as QuestionItem } from "./QuestionItem/QuestionItem"
export { default as Score } from "./Score/Score"
export { default as YellowBlob } from "./Blobs/YellowBlob/YellowBlob"
export { default as OrangeBlob } from "./Blobs/OrangeBlob/OrangeBlob"
